### PR TITLE
Use TOML.print more extensively

### PR DESCRIPTION
**Pull request by KeithWM**
I can imagine there being a reason _not_ to do this, but if so, there should be a test case embodying that reason.

### CODE REVIEW

**Comment by ufechner7** [comment]
What is the goal of this pull-request? To simplify the code?

There is a reason why I wrote the code the way I did, and this is to ensure the correct order of the sections in the Project.toml file. I did not check yet what is the resulting order when including this pull request.

**Comment by KeithWM** [comment]
The goal was indeed to simplify the code as a precursor to a second PR that would deal with maintaining existing compats.

I had an inkling it might be related to the ordering. And that is kind of hard to test because (iirc) Julia dicts do not maintain their order. I do see a solution to this by using the `by` kwarg of `TOML.print`. I will do that as soon as I have the chance.

**Comment by KeithWM** [comment]
I've adjusted the tests to check for the correct ordering of the TOML too and added an extra test case specifically for this. Subsequently adjusted the code to use a special ordering function `toml_order` that looks for fixed elements of a `Project.toml` and puts them in the expected order and returns the element name itself otherwise to maintain alphabetical ordering of dependencies and compats.

**Comment by ufechner7** [comment]
Looks good to me. :+1: 

Shall I merge it?

**Comment by KeithWM** [comment]
Let me try to fix that final CI issue. I presume writing a docstring for `toml_order` will be sufficient for that?

**Comment by ufechner7** [comment]
Actually, these instruction should work for this package, too: https://juliagraphics.github.io/QML.jl/dev/developer/

**Pull request merged**
